[package]
name = "leetcode-tui-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
reqwest = {version="0.11.18", features=["json", "cookie_crate", "cookie_store", "cookies", ]}
serde = {version = "1.0.171", features=["derive"]}
serde_json = "1.0.102"
tokio ={ version = "1.29.1", features=["macros", "rt-multi-thread"]}
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros", "with-json",  ] }
tracing-subscriber = "0.3.17"
tracing = "0.1.37"

