#:schema https://json.schemastore.org/cargo.json
[package]
name = "leetcode-tui-rs"
version = "0.3.0"
edition = "2021"
authors = ["Akarsh <akarsh.1995.02@gmail.com>"]
description = "Leetcode terminal UI. Helps you browse leetcode stats and manage your leetcode from terminal."
readme = "README.md"
repository = "https://github.com/akarsh1995/leetcode-tui"
homepage = "https://github.com/akarsh1995/leetcode-tui"
license = "MIT"
keywords = ["tui", "leetcode", "terminal", "algorithms", "cli"]
categories = ["algorithms", "command-line-utilities"]
exclude = [".github", "vhs_tapes"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
crossbeam = "*"
crossterm = { version = "^0", features = ["event-stream"] }
futures = "^0"
fuzzy-matcher = "^0"
html2text = "^0"
indexmap = "^2"
kdam = "^0"
lru = "^0"
rand = "^0"
ratatui = { version = "^0", features = ["all-widgets"] }
reqwest = { version = "^0", features = [
  "json",
  "cookie_crate",
  "cookie_store",
  "cookies",
] }
sea-orm = { version = "^0", features = [
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros",
  "with-json",
] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
strum = { version = "^0", features = ["derive"] }
thiserror = "^1"
tokio = { version = "^1", features = ["macros", "rt-multi-thread"] }
toml = "^0"
xdg = "^2"

[[bin]]
name = "leetui"
path = "src/main.rs"

[dependencies.sea-orm-migration]
version = "^0"
features = ["runtime-tokio-native-tls", "sqlx-sqlite"]

[dev-dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[profile.release]
lto = true
opt-level = "z" # Optimize for size.
